# Generated by Django 4.2 on 2023-08-28 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LearnNest', '0003_rename_room_message_nest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nest',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='nest',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
